export const ERROR_CODES = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_OPERATOR_PERMISSION: 'MISSING_OPERATOR_PERMISSION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  LOGISTICS_ONLY_FEATURE_UNAVAILABLE: 'LOGISTICS_ONLY_FEATURE_UNAVAILABLE',
  OPTIMISTIC_LOCK_FAILED: 'OPTIMISTIC_LOCK_FAILED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  TENANT_ISOLATION_VIOLATION: 'TENANT_ISOLATION_VIOLATION',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS_BY_ERROR_CODE: Record<ErrorCode, number> = {
  [ERROR_CODES.AUTHENTICATION_REQUIRED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.MISSING_OPERATOR_PERMISSION]: 403,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.IDEMPOTENCY_CONFLICT]: 409,
  [ERROR_CODES.INVALID_STATE_TRANSITION]: 422,
  [ERROR_CODES.LOGISTICS_ONLY_FEATURE_UNAVAILABLE]: 422,
  [ERROR_CODES.OPTIMISTIC_LOCK_FAILED]: 409,
  [ERROR_CODES.PAYMENT_PROVIDER_ERROR]: 502,
  [ERROR_CODES.WEBHOOK_SIGNATURE_INVALID]: 400,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.TENANT_ISOLATION_VIOLATION]: 500,
};
