export enum DeliveryType {
  SHIP = 'SHIP',
  PICKUP = 'PICKUP',
}

export enum DeliveryCarrierType {
  OWN_FLEET = 'OWN_FLEET',
  EXTERNAL_COURIER = 'EXTERNAL_COURIER',
}

export enum BuyerType {
  INDIVIDUAL = 'INDIVIDUAL',
  CORPORATE = 'CORPORATE',
}

export enum FrontendMode {
  NATIVE_RUTA = 'NATIVE_RUTA',
  CUSTOM_LANDING_BY_RUTA = 'CUSTOM_LANDING_BY_RUTA',
}

export enum PaymentMethod {
  ONLINE_AT_ORDER = 'ONLINE_AT_ORDER',
  ELECTRONIC_ON_DELIVERY = 'ELECTRONIC_ON_DELIVERY',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export enum PaymentMethodSubmethod {
  DATAFONO = 'DATAFONO',
  BANK_TRANSFER = 'BANK_TRANSFER',
  PAYMENT_LINK = 'PAYMENT_LINK',
  QR = 'QR',
}

export enum RefundModality {
  STORE_CREDIT = 'STORE_CREDIT',
  BANK_REFUND = 'BANK_REFUND',
}

export enum ReturnMechanism {
  BUYER_SHIPS_VIA_COURIER = 'BUYER_SHIPS_VIA_COURIER',
  CLIENT_PICKS_UP = 'CLIENT_PICKS_UP',
}

export enum RecurrenceMode {
  SCHEDULED_RECURRING = 'SCHEDULED_RECURRING',
  REPEAT_LAST_ORDER = 'REPEAT_LAST_ORDER',
}

export enum RecurrencePeriodicity {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM_INTERVAL = 'CUSTOM_INTERVAL',
}

export enum RecurrenceStatus {
  RECURRENCE_ACTIVE = 'RECURRENCE_ACTIVE',
  RECURRENCE_PAUSED = 'RECURRENCE_PAUSED',
  RECURRENCE_CANCELLED = 'RECURRENCE_CANCELLED',
}

export enum DisputeStatus {
  DISPUTED = 'DISPUTED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
}
