export enum PaymentStatus {
  PAYMENT_NOT_STARTED = 'PAYMENT_NOT_STARTED',
  PENDING_ONLINE_PAYMENT = 'PENDING_ONLINE_PAYMENT',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAID = 'PAID',
  PAYMENT_FAILED_RETRYABLE = 'PAYMENT_FAILED_RETRYABLE',
  PAYMENT_REJECTED_FINAL = 'PAYMENT_REJECTED_FINAL',
  PENDING_COLLECTION = 'PENDING_COLLECTION',
  COLLECTION_PROCESSING = 'COLLECTION_PROCESSING',
  PAYMENT_COLLECTED = 'PAYMENT_COLLECTED',
  PAYMENT_COLLECTION_FAILED = 'PAYMENT_COLLECTION_FAILED',
  PAYMENT_NOT_COLLECTED = 'PAYMENT_NOT_COLLECTED',
}
