export enum RefundStatus {
  REFUND_NOT_REQUIRED = 'REFUND_NOT_REQUIRED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUND_PROCESSING = 'REFUND_PROCESSING',
  REFUND_PROVIDER_REQUESTED = 'REFUND_PROVIDER_REQUESTED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUND_FAILED = 'REFUND_FAILED',
}
